### ISSUE TITLE
Ship zoom level not synced over websocket

### ISSUE THREAD

**Issue by OpenUAS** [legras/uav3i#48]
If one operator station has a big zoom, the othere.g. veto a small, the ship gets huge.

**Comment by legras** [comment]
This was by design, the reasoning was that the UAV operator would need only the big display to know where on the ship the enduser wanted to see.

But, I now see the point of having a zoomed out view in the ingress and egress phases.

I will address this in the next hour or so.

**Comment by legras** [comment]
Done in bfc1fca0.
